// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20230105005622_PrimaMigrazioneXD")]
    partial class PrimaMigrazioneXD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompitoDipendente", b =>
                {
                    b.Property<int>("ListaCompitiAssegnatiCompitoID")
                        .HasColumnType("int");

                    b.Property<string>("ListaDipendentiUsername")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ListaCompitiAssegnatiCompitoID", "ListaDipendentiUsername");

                    b.HasIndex("ListaDipendentiUsername");

                    b.ToTable("CompitoDipendente");
                });

            modelBuilder.Entity("To_Do_List.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteID");

                    b.HasIndex("ClienteID")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("To_Do_List.Compito", b =>
                {
                    b.Property<int>("CompitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompitoID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Scadenza")
                        .HasColumnType("Date");

                    b.Property<bool>("Stato")
                        .HasColumnType("bit");

                    b.HasKey("CompitoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("CompitoID")
                        .IsUnique();

                    b.ToTable("Compito");
                });

            modelBuilder.Entity("To_Do_List.Dipendente", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Dipendente");
                });

            modelBuilder.Entity("CompitoDipendente", b =>
                {
                    b.HasOne("To_Do_List.Compito", null)
                        .WithMany()
                        .HasForeignKey("ListaCompitiAssegnatiCompitoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("ListaDipendentiUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("To_Do_List.Compito", b =>
                {
                    b.HasOne("To_Do_List.Cliente", "Cliente")
                        .WithMany("ListaCommissioni")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("To_Do_List.Cliente", b =>
                {
                    b.Navigation("ListaCommissioni");
                });
#pragma warning restore 612, 618
        }
    }
}
