// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    partial class ToDoListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompitoDipendente", b =>
                {
                    b.Property<int>("ListaCompitiAssegnatiCompito_Id")
                        .HasColumnType("int");

                    b.Property<string>("ListaDipendentiUsername")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ListaCompitiAssegnatiCompito_Id", "ListaDipendentiUsername");

                    b.HasIndex("ListaDipendentiUsername");

                    b.ToTable("CompitoDipendente");
                });

            modelBuilder.Entity("To_Do_List.Cliente", b =>
                {
                    b.Property<int>("Cliente_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cliente_ID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cliente_ID");

                    b.HasIndex("Cliente_ID")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("To_Do_List.Compito", b =>
                {
                    b.Property<int>("Compito_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Compito_Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Scadenza")
                        .HasColumnType("Date");

                    b.Property<bool>("Stato")
                        .HasColumnType("bit");

                    b.HasKey("Compito_Id");

                    b.HasIndex("Cliente_ID");

                    b.HasIndex("Compito_Id")
                        .IsUnique();

                    b.ToTable("Compito");
                });

            modelBuilder.Entity("To_Do_List.Dipendente", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Dipendente");
                });

            modelBuilder.Entity("CompitoDipendente", b =>
                {
                    b.HasOne("To_Do_List.Compito", null)
                        .WithMany()
                        .HasForeignKey("ListaCompitiAssegnatiCompito_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("ListaDipendentiUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("To_Do_List.Compito", b =>
                {
                    b.HasOne("To_Do_List.Cliente", "Cliente")
                        .WithMany("ListaCommissioni")
                        .HasForeignKey("Cliente_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("To_Do_List.Cliente", b =>
                {
                    b.Navigation("ListaCommissioni");
                });
#pragma warning restore 612, 618
        }
    }
}
